name: First Workflow
on: workflow_dispatch
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: |
            echo "Hello-Man"
            echo "Hello-Lady"
      - name: GoodBye
        run: echo "See-You"
  basic1:
    needs: basic
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "Welcome Nishanth"
